In [19]:
import pandas as pd
import numpy as np

In [20]:
true_data=pd.read_csv(r'News _dataset\True.csv')
fake_data=pd.read_csv(r'News _dataset\Fake.csv')

print(true_data[0:10])
fake_data[0:4]

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) -

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017

In [21]:
print(true_data['text'][0])
true_data.columns

WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support educati

Index(['title', 'text', 'subject', 'date'], dtype='object')

In [22]:
len(true_data)


21417

In [23]:
len(fake_data)

23481

In [24]:
fake_data['label'] = 1
true_data['label']=0
print(true_data.head())
fake_data.head()

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  label  
0  December 31, 2017       0  
1  December 29, 2017       0  
2  December 31, 2017       0  
3  December 30, 2017       0  
4  December 29, 2017       0  


title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  label  
0  December 31, 2017      1  
1  December 31, 2017      1  
2  December 30, 2017      1  
3  December 29, 2017      1  
4  December 25, 2017      1

In [25]:

all_data=pd.concat([fake_data, true_data])
random_permutation = np.random.permutation(len(all_data))
all_data= all_data.iloc[random_permutation]
print(all_data.columns)
all_data.head()

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')


title  \
16365  Catalan government business head resigns over ...   
558    House ethics panel investigating allegations a...   
13544  SANCTIMONIOUS, OPEN-BORDERS PAUL RYAN Is Tanki...   
14700  German Greens want last nuclear weapons withdr...   
2873    Restaurant Owner Calls Black Customer ‘N*****...   

                                                    text       subject  \
16365  MADRID (Reuters) - The Catalan government s bu...     worldnews   
558    WASHINGTON (Reuters) - The House of Representa...  politicsNews   
13544  Will Republican voters take down sanctimonious...      politics   
14700  BERLIN (Reuters) - Greens want the next coalit...     worldnews   
2873   A Pennsylvania restaurant owner is under fire ...          News   

                     date  label  
16365   October 26, 2017       0  
558    November 21, 2017       0  
13544        Jul 10, 2016      1  
14700  November 15, 2017       0  
2873     January 24, 2017      1

In [26]:
filterd_data=all_data.loc[:, ['title', 'text', "subject", 'label']]
filterd_data.head()

title  \
16365  Catalan government business head resigns over ...   
558    House ethics panel investigating allegations a...   
13544  SANCTIMONIOUS, OPEN-BORDERS PAUL RYAN Is Tanki...   
14700  German Greens want last nuclear weapons withdr...   
2873    Restaurant Owner Calls Black Customer ‘N*****...   

                                                    text       subject  label  
16365  MADRID (Reuters) - The Catalan government s bu...     worldnews      0  
558    WASHINGTON (Reuters) - The House of Representa...  politicsNews      0  
13544  Will Republican voters take down sanctimonious...      politics      1  
14700  BERLIN (Reuters) - Greens want the next coalit...     worldnews      0  
2873   A Pennsylvania restaurant owner is under fire ...          News      1

In [27]:
filterd_data.isnull().sum()

title      0
text       0
subject    0
label      0
dtype: int64

In [28]:
filterd_data['training_feature']=filterd_data['title']+' '+filterd_data['text']+' '+filterd_data['subject']
filterd_data.head()

title  \
16365  Catalan government business head resigns over ...   
558    House ethics panel investigating allegations a...   
13544  SANCTIMONIOUS, OPEN-BORDERS PAUL RYAN Is Tanki...   
14700  German Greens want last nuclear weapons withdr...   
2873    Restaurant Owner Calls Black Customer ‘N*****...   

                                                    text       subject  label  \
16365  MADRID (Reuters) - The Catalan government s bu...     worldnews      0   
558    WASHINGTON (Reuters) - The House of Representa...  politicsNews      0   
13544  Will Republican voters take down sanctimonious...      politics      1   
14700  BERLIN (Reuters) - Greens want the next coalit...     worldnews      0   
2873   A Pennsylvania restaurant owner is under fire ...          News      1   

                                        training_feature  
16365  Catalan government business head resigns over ...  
558    House ethics panel investigating allegations a...  
13544  SANCTIMONIOUS, OPEN-BORDERS PAUL RYAN Is Tanki...  
14700  German Greens want last nuclear weapons withdr...  
2873    Restaurant Owner Calls Black Customer ‘N*****...

In [29]:
X= filterd_data['training_feature'].values
y = filterd_data['label']


In [30]:
l_X=filterd_data['training_feature'].values[0:1000]
l_Y= filterd_data['label'].values[0:1000]

In [31]:
print(l_X.shape)
print(l_Y.shape)
type (l_X)

(1000,)
(1000,)


numpy.ndarray

In [32]:
print(X[0:1])

['Catalan government business head resigns over independence strategy MADRID (Reuters) - The Catalan government s business head resigned on Thursday, a government source said, after regional president Carles Puigdemont ruled out elections and left the possibility of a unilateral declaration of independence from Spain. Santi Vila had said he was opposed to such a declaration and La Vanguardia newspaper reported he favored regional elections.  worldnews']


In [33]:
# from sklearn import preprocessing

# print(X.shape)
# print(type(X))
# # print(X[0:1])
# X=X.reshape((1,-1))
# X = preprocessing.normalize(X)
# np.random.shuffle(X)
# print(X.shape)
# print(type(X))

# X = preprocessing.normalize([X.reshape(1,-1)])


In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

ValueError: bad marshal data (unknown type code)

In [ ]:
vectorizer= TfidfVectorizer()
X=vectorizer.fit_transform(X)

In [ ]:
l_vectorizer= TfidfVectorizer()
l_X=l_vectorizer.fit_transform(l_X)

In [ ]:
print(type(X))
print(X.shape)
print(type(l_X))
print(l_X.shape)


<class 'scipy.sparse._csr.csr_matrix'>
(44898, 122516)
<class 'scipy.sparse._csr.csr_matrix'>
(1000, 22107)


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, stratify=y, random_state=42)

In [ ]:
l_X_train, l_X_test, l_Y_train, l_Y_test = train_test_split(l_X, l_Y, test_size = 0.2, random_state=42)

In [ ]:
X_train.shape


(35918, 122516)

In [ ]:
model=LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
# Model accuracy on the test set
test_y_hat=model.predict(X_test)
print(accuracy_score(test_y_hat, Y_test))

# Model Accuracy on  training set
train_y_hat = model.predict(X_train)
print(accuracy_score(train_y_hat,Y_train))

0.9910913140311804
0.9946266495907344


In [ ]:
def predict(input_data):
    
    y_hat= model.predict(input_data)
    if y_hat==0:
        return "The article is Fake"
    else:
        return 'The article is not Fake'

In [17]:
print(predict(X_test[2000]))
model.predict(X_test[2000])[0]

NameError: name 'predict' is not defined

In [29]:
from sklearn.metrics import precision_score, recall_score, f1_score

print (precision_score(Y_train, train_y_hat,))
print (recall_score(Y_train, train_y_hat,))
print(f1_score(Y_train, train_y_hat,))


print (precision_score(Y_test, test_y_hat,))
print (recall_score(Y_test, test_y_hat,))
print(f1_score(Y_test, test_y_hat,))

0.9951001278227525
0.9946233697098749
0.9948616916482522
0.9929517300299018
0.9899914821124361
0.9914693964597995


In [30]:
from sklearn.metrics import confusion_matrix
print ([['TP', 'FP'],['FN', 'TN']])
print(confusion_matrix(Y_test, test_y_hat,))
print (confusion_matrix(Y_train, train_y_hat,))

[['TP', 'FP'], ['FN', 'TN']]
[[4251   33]
 [  47 4649]]
[[17041    92]
 [  101 18684]]


In [31]:
from sklearn import svm

#Create a svm Classifier
model = svm.SVC(kernel='linear') # Linear Kernel
clf_poly=clf = svm.SVC(kernel='poly') # Polynomial kernel


In [32]:
print(X_train.shape)
# X_train.iloc[0:1000].shape



(35918, 122516)


In [33]:
#Train the model using the training sets
model.fit(l_X_train, l_Y_train)
# clf_poly.fit(X_train,Y_train)



SVC(kernel='linear')

In [34]:
#Predict the response for test dataset
y_pred = model.predict(l_X_test)

In [35]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))


0.975
0.9900990099009901
0.9615384615384616
0.975609756097561
[[ 95   1]
 [  4 100]]


In [36]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(l_X_train, l_Y_train)



RandomForestClassifier()

In [37]:
y_pred = model.predict(l_X_test)



In [38]:
print (y_pred)

[0 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 0 0 1
 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 0 0
 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0
 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1
 1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 0
 0 0 0 1 1 0 1 1 1 1 0 1 0 0 1]


In [39]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score,confusion_matrix


print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))


0.99
1.0
0.9807692307692307
0.9902912621359222
[[ 96   0]
 [  2 102]]


In [40]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()


In [41]:
# X_train.todense()
# model2=GaussianNB()
# model2.fit(X_train.toarray(), Y_train)

In [42]:
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [43]:
model.fit(l_X_train.toarray(), l_Y_train)


GaussianNB()

In [44]:
y_pred = model.predict(l_X_test.toarray())


In [45]:
print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))


0.815
0.7637795275590551
0.9326923076923077
0.8398268398268398
[[66 30]
 [ 7 97]]
